name: dev-pipeline
on: 
  pull_request:
    branches:
      - main
    paths:
      - Environment/dev/**
  push: 
    branches:
      - main
    paths:
      - Environment/dev/**

permissions:
  id-token: write
  contents: read
jobs:
  terraform_Build_Job:
    name: Build_Job
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with: 
          client-id: 62ae0827-af1e-4cf0-bf68-c840b2ececc1
          tenant-id: 53d3cbff-d536-48df-a6c7-62dbac64b38b
          subscription-id: ae14f047-f613-4f71-8ea9-6defaf5c695d

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: Environment/dev
    
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: Environment/dev
        
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: Environment/dev
    
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        working-directory: Environment/dev

  terraform_Deploy_Job:
    name: Deploy_Job
    runs-on: self-hosted
    needs: terraform_Build_Job
    if: needs.terraform_Build_Job.result == 'success' && github.ref == 'refs/heads/main'
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with: 
          client-id: 62ae0827-af1e-4cf0-bf68-c840b2ececc1
          tenant-id: 53d3cbff-d536-48df-a6c7-62dbac64b38b
          subscription-id: ae14f047-f613-4f71-8ea9-6defaf5c695d

      
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: Environment/dev

      - name: Terraform apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: Environment/dev
        
  
    

        
       
        
    
